from enum import Enum


class Team(Enum):
    CELTICS = "Boston", "Celtics", "BOS", "bos.png"
    NETS = "Brooklyn", "Nets", "BRK", "bkn.png"
    KNICKS = "New York", "Knicks", "NYK", "ny.png"
    SIXERS = "Philadelphia", "Sixers", "PHI", "phi.png"
    RAPTORS = "Toronto", "Raptors", "TOR", "tor.png"
    BULLS = "Chicago", "Bulls", "CHI", "chi.png"
    CAVALIERS = "Cleveland", "Cavaliers", "CLE", "cle.png"
    PISTONS = "Detroit", "Pistons", "DET", "det.png"
    PACERS = "Indiana", "Pacers", "IND", "ind.png"
    BUCKS = "Milwaukee", "Bucks", "MIL", "mil.png"
    HAWKS = "Atlanta", "Hawks", "ATL", "atl.png"
    HORNETS = "Charlotte", "Hornets", "CHO", "cha.png"
    HEAT = "Miami", "Heat", "MIA", "mia.png"
    MAGIC = "Orlando", "Magic", "ORL", "orl.png"
    WIZARDS = "Washington", "Wizards", "WAS", "wsh.png"
    NUGGETS = "Denver", "Nuggets", "DEN", "den.png"
    WOLVES = "Minnesota", "Timberwolves", "MIN", "min.png"
    THUNDER = "Oklahoma City", "Thunder", "OKC", "okc.png"
    BLAZERS = "Portland", "Trailblazers", "POR", "chi.png"
    JAZZ = "Utah", "Jazz", "UTA", "utah.png"
    WARRIORS = "Golden State", "Warriors", "GSW", "gs.png"
    CLIPPERS = "Los Angeles", "Clippers", "LAC", "lac.png"
    LAKERS = "Los Angeles", "Lakers", "LAL", "lal.png"
    SUNS = "Phoenix", "Suns", "PHO", "phx.png"
    KINGS = "Sacramento", "Kings", "SAC", "sac.png"
    MAVERICKS = "Dallas", "Mavericks", "DAL", "dal.png"
    ROCKETS = "Houston", "Rockets", "HOU", "hou.png"
    GRIZZLIES = "Memphis", "Grizzlies", "MEM", "mem.png"
    PELICANS = "New Orleans", "Pelicans", "NOP", "no.png"
    SPURS = "San Antonio", "Spurs", "SAS", "sa.png"

    def logo(self) -> str:
        return f"https://a.espncdn.com/combiner/i?img=/i/teamlogos/nba/500/{self.value[3]}&h=25&w=25"
