from enum import Enum


class Team(Enum):
    CELTICS = "Boston Celtics", "BOS"
    NETS = "Brooklyn Nets", "BRK"
    KNICKS = "New York Knicks", "NYK"
    SIXERS = "Philadelphia Sixers", "PHI"
    RAPTORS = "Toronto Raptors", "TOR"
    BULLS = "Chicago Bulls", "CHI"
    CAVALIERS = "Cleveland Cavaliers", "CLE"
    PISTONS = "Detroit Pistons", "DET"
    PACERS = "Indiana Pacers", "IND"
    BUCKS = "Milwaukee Bucks", "MIL"
    HAWKS = "Atlanta Hawks", "ATL"
    HORNETS = "Charlotte Hornets", "CHO"
    HEAT = "Miami Heat", "MIA"
    MAGIC = "Orlando Magic", "ORL"
    WIZARDS = "Washington Wizards", "WAS"
    NUGGETS = "Denver Nuggets", "DEN"
    WOLVES = "Minnesota Timberwolves", "MIN"
    THUNDER = "Oklahoma City Thunder", "OKC"
    BLAZERS = "Portland Trailblazers", "POR"
    JAZZ = "Utah Jazz", "UTA"
    WARRIORS = "Golden State Warriors", "GSW"
    CLIPPERS = "Los Angeles Clippers", "LAC"
    LAKERS = "Los Angeles Lakers", "LAL"
    SUNS = "Phoenix Suns", "PHO"
    KINGS = "Sacramento Kings", "SAC"
    MAVERICKS = "Dallas Mavericks", "DAL"
    ROCKETS = "Houston Rockets", "HOU"
    GRIZZLIES = "Memphis Grizzlies", "MEM"
    PELICANS = "New Orleans Pelicans", "NOP"
    SPURS = "San Antonio Spurs", "SAS"
